### ISSUE TITLE
oc.login error

### ISSUE THREAD

**Issue by schaefer0** [owncloud/pyocclient#102]
I'm trying to isolate whether this is your library or a python version problem interacting with openssl
Python version is 2.7.9.
$ python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
-> OpenSSL 1.0.1e 11 Feb 2013
This is the latest returned by apt-get. Any help would be appreciated.
>>> oc.login("name","password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyocclient-0.1-py2.7.egg/owncloud/owncloud.py", line 213, in login
    res = self.__session.get(self.url + 'index.php')
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by PVince81** [comment]
pyocclient is using the requests library (http://docs.python-requests.org/en/latest/).

I just tired locally and strangely I'm getting another error:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    oc.login('PVince81', 'REMOVED')
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 213, in login
    res = self.__session.get(self.url + 'index.php')
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 21] Is a directory
```

but this might be another issue.

pyocclient logs in by connecting to the index.php page and sending basic auth.
I have:
- openSUSE Factory
- openssl-1.0.2a-1.1.x86_64
- python-requests-2.6.0-51.1.noarch
- python-2.7.10-48.1.x86_64

@Gomez did pyocclient work for you with SSL ?

@schaefer0 you could try upgrading the openssl library ?

**Comment by Gomez** [comment]
@schaefer0 You have a self signed cert? 

There is a option to disable Cert check: In the request docs there should something like this: verify=False

**Comment by Gomez** [comment]
@PVince81 A older version works for sure. Need to update and test.

**Comment by PVince81** [comment]
To disable cert checking, pass  `verify_certs=False` the constructor of the Client class.

In my test case they weren't self-signed certificates but valid ones (two servers), so maybe that's another bug.

**Comment by PVince81** [comment]
Raised my error as a separate ticket https://github.com/owncloud/pyocclient/issues/103

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
