### ISSUE TITLE
SSL Error "is a directory"

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#103]
I have two servers with valid SSL certificates.

When connecting to either of them, I'm getting this error:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    oc.login('PVince81', 'REMOVED')
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 213, in login
    res = self.__session.get(self.url + 'index.php')
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 428, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 21] Is a directory
```

**Comment by PVince81** [comment]
Hmmm, possibly a bug in my distro (openSUSE Factory) or of any of the libraries, see http://lists.opensuse.org/opensuse-factory/2015-01/msg00454.html

**Comment by PVince81** [comment]
Was a bug in my distro, has been resolved since.
