### ISSUE TITLE
example file link raises 403 error while using self signed cert

### ISSUE THREAD

**Issue by vfulco** [owncloud/pyocclient#137]
link_info = oc.share_file_with_link('testdir/remotefile.txt')

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/owncloud/__init__.py", line 460, in share_file_with_link
    self.__check_ocs_status(tree)
  File "/usr/local/lib/python2.7/dist-packages/owncloud/__init__.py", line 574, in __check_ocs_status
    raise ResponseError(int(code_el.text))
owncloud.ResponseError: HTTP error: 403

# 

Somewhat new to https: and self-signed, since i can login after passing the verify certs = false option, is this error a function of server side encryption being on?  TIA.

**Comment by PVince81** [comment]
If you are using a self-signed certificate, then currently the only way is to disable certificate verification.

I suppose it might be possible to tell the "requests" library to use a locally known certificate but have currently no idea how to do it and whether it is possible.

**Comment by PVince81** [comment]
Tagging as enhancement to look into a way for providing known certificates.

**Comment by vfulco** [comment]
Thanks for the very timely response.  This is a dev server so I was
going the el cheapo route.  Will probably try the "Let's Encrypt"
scheme in the very near future.

-- 
Vince Fulco, CFA, CAIA
612.424.5477 (universal)
186.1694.0908 (mobile in China)
vfulco1@gmail.com
wechat: vfulco
fastmail: vfulco1@fastmail.fm

--
"Don't waste what others desperately seek." -Sarita Alston
--

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
