### ISSUE TITLE
Failing test test_share_with_group against stable7

### ISSUE THREAD

**Issue by PVince81** [owncloud/pyocclient#139]
```
ERROR: test_share_with_group (__main__.TestFileAccess)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/unittest_data_provider/__init__.py", line 7, in repl

    fn(self, *i)

  File "owncloud/test/test.py", line 614, in test_share_with_group

    share_info = self.client.share_file_with_group(path, self.test_group)

  File "/home/travis/build/owncloud/pyocclient/owncloud/owncloud.py", line 1210, in share_file_with_group

    self.__check_ocs_status(tree)

  File "/home/travis/build/owncloud/pyocclient/owncloud/owncloud.py", line 1427, in __check_ocs_status

    raise OCSResponseError(r)

OCSResponseError: OCS error: 403
```

@cosenal this test was added by you, I merged it on master.

Not sure if it's due to the test or if it's a bug on OC 7...

CC @SergioBertolinSG

**Comment by PVince81** [comment]
Probably because OC 7 did not have the provisioning API so could not auto-create that group
