### ISSUE TITLE
tests fail on get_share with latest master

### ISSUE THREAD

**Issue by cosenal** [owncloud/pyocclient#145]
This happens with latest core master

```
................('Assertion error caught with data set ', ['test.txt'])
F('Assertion error caught with data set ', ['test.txt'])
F................................................
======================================================================
FAIL: test_get_share_public_link (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/acosenti/.virtualenvs/pyocenv/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 699, in test_get_share_public_link
    self.assertIsInstance(sinfo, owncloud.ShareInfo)
AssertionError: None is not an instance of <class owncloud.owncloud.ShareInfo at 0x7f84a5a132c0>

======================================================================
FAIL: test_get_share_user (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/acosenti/.virtualenvs/pyocenv/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 673, in test_get_share_user
    self.assertIsInstance(sinfo, owncloud.ShareInfo)
AssertionError: None is not an instance of <class owncloud.owncloud.ShareInfo at 0x7f84a5a132c0>

----------------------------------------------------------------------
Ran 66 tests in 313.785s

FAILED (failures=2)
```

**Comment by PVince81** [comment]
It used to work, so maybe something changed on master recently. Should be possible to bisect.

**Comment by PVince81** [comment]
Works for me, closing
