### ISSUE TITLE
problem with ./runtests.sh 

### ISSUE THREAD

**Issue by yavama** [owncloud/pyocclient#147]
i've got this while runing ./runtests.sh 
is that due to my config file ? 

.......E.......FEEEEFE.E.........EEFEEEEE............('Assertion error caught with data set ', ('attr1', 'value1'))
F.F..ssssssss
======================================================================
ERROR: test_delete_share (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 630, in test_delete_share
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "/usr/local/lib/python2.7/dist-packages/pyocclient-0.1-py2.7.egg/owncloud/owncloud.py", line 1233, in share_file_with_user
    self.__check_ocs_status(tree)
  File "/usr/local/lib/python2.7/dist-packages/pyocclient-0.1-py2.7.egg/owncloud/owncloud.py", line 1581, in __check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 999

======================================================================
ERROR: test_get_share_public_link (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 694, in test_get_share_public_link
    sinfo_run = self.client.share_file_with_link(path)
  File "/usr/local/lib/python2.7/dist-packages/pyocclient-0.1-py2.7.egg/owncloud/owncloud.py", line 817, in share_file_with_link
    self.__check_ocs_status(tree)
  File "/usr/local/lib/python2.7/dist-packages/pyocclient-0.1-py2.7.egg/owncloud/owncloud.py", line 1581, in __check_ocs_status
    raise OCSResponseErro

**Comment by PVince81** [comment]
@yavama which ownCloud version ?

**Comment by yavama** [comment]
it's owncloud-5.0.9

**Comment by LukasReschke** [comment]
@yavama ownCloud 5.x is end-of-life, please update.

**Comment by PVince81** [comment]
I'll update the README, sorry for confusion.

**Comment by yavama** [comment]
in fact i was installing pyOwncloud but it doesn't work
does pyocclient replace it ? 
i'm confused

**Comment by PVince81** [comment]
@yavama pyocclient makes it possible for you to write python scripts that connect to an existing ownCloud instance. So you will need a running ownCloud instance to use it.

**Comment by PVince81** [comment]
ah sorry. pyOwncloud is not the same as pyocclient.

pyOwncloud implements file syncing.
pyoclient is just a library to make it easier to call API operations on an ownCloud server.

**Comment by yavama** [comment]
thank you for clarify it to me :)

**Comment by yavama** [comment]
thank you for the clarification :)
