### ISSUE TITLE
Pip installation fails due to decoding error

### ISSUE THREAD

**Issue by amicitas** [owncloud/pyocclient#196]
Installation of `pyocclient-0.4` using `pip` currently fails.  I am trying to install with `Python 3.6.1` and `pip 9.0.1' on OS X.   The error I get is:

```
Collecting pyocclient
  Downloading pyocclient-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-q2zi2pbp/pyocclient/setup.py", line 18, in <module>
        + '\n')
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 229: ordinal not in range(128)
```

The issue is that `CONTRIBUTORS.rst` contains `utf-8` characters, but the setup script is not automatically attempting to read the file with a `utf-8' encoding.

**Comment by amicitas** [comment]
I have a created a pull-request that resolves this issue: [pull request #197](https://github.com/owncloud/pyocclient/pull/197)
