### ISSUE TITLE
problem with share_file_with_link()

### ISSUE THREAD

**Issue by Arctixc** [owncloud/pyocclient#203]
I tried uploading a file with put_file(), the file name contained an 'ü', everything worked fine, but when I tried using the share_file_with_link() function i get an error. When the file name doesnt contain any special characters it works fine.

ERROR:

> Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python2732\lib\lib-tk\Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "getdlink.py", line 100, in <lambda>
    Buttonpw = ttk.Button(text = 'Downloadlink erzeugen',command = lambda: getLink(entrypw.get())).pack()
  File "getdlink.py", line 75, in getLink
    link_info = oc.share_file_with_link(path_nc,**kwargs)
  File "C:\Python2732\lib\site-packages\owncloud\owncloud.py", line 829, in share_file_with_link
    self._check_ocs_status(tree)
  File "C:\Python2732\lib\site-packages\owncloud\owncloud.py", line 1602, in _check_ocs_status
    raise OCSResponseError(r)
OCSResponseError: OCS error: 404

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
