### ISSUE TITLE
HTTP error : 502 with oc.login()

### ISSUE THREAD

**Issue by AlexMazars** [owncloud/pyocclient#210]
Hello,

I have an erro while using oc.login('user','password'). It returns the following error : 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/owncloud/owncloud.py", line 358, in login
    raise e
owncloud.owncloud.HTTPResponseError: HTTP error: 502
`
What could it be ?

**Comment by PVince81** [comment]
Likely a problem with your server setup: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502

Do you have local proxy settings set ?

**Comment by AlexMazars** [comment]
Yes, i tried to use export HTTP_PROXY and HTTPS_PROXY but same result

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
