### ISSUE TITLE
Max retries exceeded with url: /ocs/v1.php/cloud/capabilities (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#217]
```
$ sudo mount.davfs https://b2drop.eudat.eu/remote.php/webdav/ oc
Please enter the username to authenticate with server
https://b2drop.eudat.eu/remote.php/webdav/ or hit enter for none.
  Username:
Please enter the password to authenticate user alper.alimoglu@boun.edu.tr with server
https://b2drop.eudat.eu/remote.php/webdav/ or hit enter for none.
  Password:
mount.davfs: the server certificate is not trusted
  issuer:      TERENA, Amsterdam, Noord-Holland, NL
  subject:     CSC - Tieteen tietotekniikan keskus Oy, Espoo, FI
  identity:    b2drop.eudat.eu
  fingerprint: c9:93:f5:d1:07:5e:b5:bc:bd:71:92:fa:f4:8d:bf:75:db:24:55:6c
You only should accept this certificate, if you can
verify the fingerprint! The server might be faked
or there might be a man-in-the-middle-attack.
Accept certificate for this session? [y,N] y
mount.davfs: warning: the server does not support locks
```

------------------

```
oc = owncloud.Client('https://b2drop.eudat.eu/');
oc.login('user@emial', password);
```
gives following error:

```
Traceback (most recent call last):
  File "shareOwnCloud.py", line 13, in <module>
    oc.login('alper.alimoglu@boun.edu.tr', '33nEKSEV02!');
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 354, in login
    self._update_capabilities()
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1795, in _update_capabilities
    'capabilities'
  File "/usr/local/lib/python2.7/dist-packages/owncloud/owncloud.py", line 1649, in _make_ocs_request
    res = self._session.request(method, self.url + path, **attributes)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='b2drop.eudat.eu', port=443): Max retries exceeded with url: /ocs/v1.php/cloud/capabilities (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```

Using `oc`how could I accept/trust the certificate like I do while mount.

**Comment by PVince81** [comment]
please try with https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L322 and set it to false

For self signed certificates there is no mechanism in pyocclient to make it accept it.
Not sure if it needs an extension or whether it's possible to feed the certificate directly to the "requests" library.

**Comment by inffbl** [comment]
@avatar-lavventura is it resolved? I have almost the same problem, I can't upload files

<class 'requests.exceptions.SSLError'> File: test_upload.py Line: 22
HTTPSConnectionPool(host='drive.immobisp.com', port=443): Max retries exceeded with url: /remote.php/webdav/MSQoS4/03%20Flash%20Report/Periode%20Test/Zona_21/BADUNG/DT/FR_Indosat.xlsx (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2393)')))

**Comment by avatar-lavventura** [comment]
@inffbl It has been a long time since I had this issue. But I have not get this error since than looks like it has been resolved.

**Comment by marward** [comment]
@avatar-lavventura @inffbl facing the same issue right now. Trying to list all files in remote folder. Maybe there are some limits in Nextcloud instance?
