### ISSUE TITLE
Login: xml.etree.ElementTree.ParseError: no element found: line 1, column 0

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#240]
When I try to login I get following error:

```
>>>import owncloud

>>> oc = owncloud.Client("https://b2drop.eudat.eu/")
>>>oc.login("059ab6ba-4030-48bb-b81b-12115f531296", "12345")

Traceback (most recent call last):
  File "zoo.py", line 4, in <module>
    oc.login("059ab6ba-4030-48bb-b81b-12115f531296", "qPzE2-An4Dz-zdLeK-7Cx4w-iKJm9")
  File "/Users/alper/venv/lib/python3.7/site-packages/owncloud/owncloud.py", line 354, in login
    self._update_capabilities()
  File "/Users/alper/venv/lib/python3.7/site-packages/owncloud/owncloud.py", line 1798, in _update_capabilities
    tree = ET.fromstring(res.content)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementTree.py", line 1316, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

What may cause this error? is there any way to prevent it?

**Comment by BurnySc2** [comment]
Excuse me for digging out an old issue, but I just had this problem and it was due to using [authelia](https://www.authelia.com/) and hidng my owncloud behind a middleware via a one_factor authentification.
Hope this helps to people accidently setting this up and forgetting about it.

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
