### ISSUE TITLE
owncloud.owncloud.HTTPResponseError: HTTP error: 401

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#242]
I am using `pyocclient` to login into eudat-b2drop(https://b2drop.eudat.eu/). I was login into my account and upload files, create folders without any problem.

I started to get `owncloud.owncloud.HTTPResponseError: HTTP error: 401` which I never used to get before. What might be the reason for this error? Pleasen note that I am still able to login in to mount account, and also mount it in order to create and upload folders.

```
Traceback (most recent call last):
  File "./submit.py", line 47, in submit
    folder_hash = eudat.initialize_folder(folder, oc)
  File "/home/libs/eudat.py", line 137, in initialize_folder
    print(oc.mkdir(tar_hash))
  File "/home/pthon3.6/site-packages/owncloud/owncloud.py", line 633, in mkdir
    return self._make_dav_request('MKCOL', path)
  File "/home/venv/lib/python3.6/site-packages/owncloud/owncloud.py", line 1679, in _make_dav_request
    raise HTTPResponseError(res)
owncloud.owncloud.HTTPResponseError: HTTP error: 401
```

**Comment by avatar-lavventura** [comment]
Sorry it was due to unauthorized access. I have used the correct password and all works fine.
