### ISSUE TITLE
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5abcb3c5d0>: Failed to establish a new connection: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/pyocclient#251]
I am trying to connect into owncloud using following script, where I am storing `oc` object into a file ; and re-use the same one.

```
 oc = owncloud.Client("https://b2drop.eudat.eu/")
with open(password_path, "r") as content_file:
    password = content_file.read().strip()

oc.login(user, password)  # May take long time to connect
password = ""
f = open(fname, "wb")
pickle.dump(oc, f)
f.close()
```

---------

During my tests this works but when I run the same script over and over again I may get following error:

```
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/home/alper/venv/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5abcb3c5d0>: Failed to establish a new connection: [Errno 110] Connection timed out
```

=> Is there any way to prevent this error to happening ?

**Comment by luffah** [comment]
IMHO the reject is done by the server, therefore it doesn't really have its place in bugs.

Best way would be to proxy the connection, to limit logins... or maybe there is another way .. like making a share link and downloading with `<share url>/download`.

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
