### ISSUE TITLE
Error 401 when trying to do operations in shared folder that is password protected. 

### ISSUE THREAD

**Issue by Attackly** [owncloud/pyocclient#282]
Hey, 

when i want to access a password protected share like this 

```python
oc = owncloud.Client.from_public_link(theHost, folder_password=thepassword)
oc.list("")
```
I recive this error: 
```
Traceback (most recent call last):
  File "C:\Users\me\PycharmProjects\pyocclienttest\main.py", line 4, in <module>
    oc.list("")
  File "C:\Users\me\PycharmProjects\pyocclienttest\venv\Lib\site-packages\owncloud\owncloud.py", line 469, in list
    res = self._make_dav_request('PROPFIND', path, headers=headers, data=data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\PycharmProjects\pyocclienttest\venv\Lib\site-packages\owncloud\owncloud.py", line 1815, in _make_dav_request
    raise HTTPResponseError(res)
owncloud.owncloud.HTTPResponseError: HTTP error: 401
```

I have fiddled around a bit.  
I got it to work by adding this header to the list and get_file function.
headers={"X-Requested-With" : "XMLHttpRequest"}

Does someone have the same problem or can confirm it?

**Comment by Jasonthefirst** [comment]
Hi, 
How did you add the header? You mean you added the header to the source or can you give the header to the client? I have the same error to a publicly shared nextcloud folder.
Edit: 
Found it: oc._session.headers.update({"X-Requested-With": "XMLHttpRequest"})

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
