### ISSUE TITLE
login to server not possible (invalid token)

### ISSUE THREAD

**Issue by nnako** [owncloud/pyocclient#286]
Hi,

I use pyocclient for some years to automate file management on a NextCloud server using a small RaspberryPi GNU/Linux computer. On this system I finally could not get a NextCloud Client to run properly. So I had to switch to manual use of the `pyocclient` module.

Since yesterday, the login of `pyocclient` fails, although neither the credentials deposited on the server nor the credentials given to the `login()` function changed. The error message looks like this:

```python
>>> oc = owncloud.Client('<url>')
>>> oc.login('<user>', '<pass>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/APP__filesync/_venv/lib/python3.7/site-packages/owncloud/owncloud.py", line 362, in login
    self._update_capabilities()
  File "/home/pi/APP__filesync/_venv/lib/python3.7/site-packages/owncloud/owncloud.py", line 1934, in _update_capabilities
    tree = ET.fromstring(res.content)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 9
```

Seems like the login requirements on the server side decided to not comply to the concept implemented within `pyocclient` anymore. Maybe because of a "silent" NextCloud update on the server side. With "proper" NextCloud clients, I can still login to the NextCloud server using the same login credentials.

**Does anybody know about such new incompatibilities?**

Thanks.

**Comment by bigcat88** [comment]
> Seems like the login requirements on the server side decided to not comply to the concept implemented within `pyocclient` anymore.

Did you tried [nc_py_api](https://github.com/cloud-py-api/nc_py_api)?

**Comment by DeepDiver1975** [comment]
This repository is being archived and is no longer maintained. Closing this as part of archival. Thank you for your contribution.
