### ISSUE TITLE
Unit tests fail against ownCloud 8.1pre-alpha (last master)

### ISSUE THREAD

**Issue by cosenal** [owncloud/pyocclient#84]
This is the log:

```
..E...........F...........EF..E............
======================================================================
ERROR: test_delete_share (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/acosenti/.virtualenvs/pyocenv/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 477, in test_delete_share
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 830, in share_file_with_user
    self.__check_ocs_status(tree)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 1156, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403

======================================================================
ERROR: test_share_with_user (__main__.TestFileAccess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/acosenti/.virtualenvs/pyocenv/lib/python2.7/site-packages/unittest_data_provider/__init__.py", line 7, in repl
    fn(self, *i)
  File "owncloud/test/test.py", line 461, in test_share_with_user
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 830, in share_file_with_user
    self.__check_ocs_status(tree)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 1156, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403

======================================================================
ERROR: test_update_share_user (__main__.TestFileAccess)
Test updating a share parameters - user share
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 547, in test_update_share_user
    share_info = self.client.share_file_with_user(path, self.share2user)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 830, in share_file_with_user
    self.__check_ocs_status(tree)
  File "build/bdist.linux-x86_64/egg/owncloud/owncloud.py", line 1156, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 403

======================================================================
FAIL: test_is_shared_not_shared_path (__main__.TestFileAccess)
Test is_shared - path does exist, but it's not shared yet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 493, in test_is_shared_not_shared_path
    self.assertFalse(self.client.is_shared(path))
AssertionError: True is not false

======================================================================
FAIL: test_update_share_password (__main__.TestFileAccess)
Test updating a share parameters - password
----------------------------------------------------------------------
Traceback (most recent call last):
  File "owncloud/test/test.py", line 601, in test_update_share_password
    self.assertIsNotNone(share_info['share_with_displayname'])
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 43 tests in 64.348s

FAILED (failures=2, errors=3)
```

**Comment by PVince81** [comment]
Locally or on Travis ? If you used SQLite for the server, this is likely due to the fileid recycling issue, see https://github.com/owncloud/core/pull/14665
Once that PR is merged all should still work properly.

Also, did you manually create the "share" user ? (back then there was no provisioning API so it couldn't be done automatically)

**Comment by cosenal** [comment]
I didn't have the "share" user, I see only one Fail now (that must be due to SQLite).
I guess this calls for a PR to update the tests to the provisioning API...

**Comment by PVince81** [comment]
This was a while ago, they should run now against master now that the SQLite fix is in

**Comment by PVince81** [comment]
Tested locally with ownCloud master + sqlite, and pyocclient master.
Works, closing.
